imports:
  - { resource: '../../../vendor/symplify/easy-coding-standard/config/set/symfony.php', ignore_errors: not_found }
  - { resource: '../../../../../symplify/easy-coding-standard/config/set/symfony.php', ignore_errors: not_found }

services:
  PhpCsFixer\Fixer\Phpdoc\AlignMultilineCommentFixer: ~
  PhpCsFixer\Fixer\Whitespace\ArrayIndentationFixer: ~
  PhpCsFixer\Fixer\Whitespace\BlankLineBeforeStatementFixer: ~
  PhpCsFixer\Fixer\LanguageConstruct\CombineConsecutiveIssetsFixer: ~
  PhpCsFixer\Fixer\LanguageConstruct\CombineConsecutiveUnsetsFixer: ~
  PhpCsFixer\Fixer\Whitespace\CompactNullableTypehintFixer: ~
  PhpCsFixer\Fixer\StringNotation\EscapeImplicitBackslashesFixer: ~
  PhpCsFixer\Fixer\LanguageConstruct\ExplicitIndirectVariableFixer: ~
  PhpCsFixer\Fixer\StringNotation\ExplicitStringVariableFixer: ~
  PhpCsFixer\Fixer\Import\FullyQualifiedStrictTypesFixer: ~
  PhpCsFixer\Fixer\StringNotation\HeredocToNowdocFixer: ~
  PhpCsFixer\Fixer\FunctionNotation\MethodArgumentSpaceFixer:
    on_multiline: ensure_fully_multiline
  PhpCsFixer\Fixer\Whitespace\MethodChainingIndentationFixer: ~
  PhpCsFixer\Fixer\Comment\MultilineCommentOpeningClosingFixer: ~
  PhpCsFixer\Fixer\Semicolon\MultilineWhitespaceBeforeSemicolonsFixer:
    strategy: new_line_for_chained_calls
  PhpCsFixer\Fixer\ControlStructure\NoAlternativeSyntaxFixer: ~
  PhpCsFixer\Fixer\StringNotation\NoBinaryStringFixer: ~
  PhpCsFixer\Fixer\Whitespace\NoExtraBlankLinesFixer:
    tokens:
      - 'break'
      - 'continue'
      - 'curly_brace_block'
      - 'extra'
      - 'parenthesis_brace_block'
      - 'return'
      - 'square_brace_block'
      - 'throw'
      - 'use'
  PhpCsFixer\Fixer\ClassNotation\NoNullPropertyInitializationFixer: ~
  PhpCsFixer\Fixer\PhpTag\NoShortEchoTagFixer: ~
  PhpCsFixer\Fixer\ControlStructure\NoSuperfluousElseifFixer: ~
  PhpCsFixer\Fixer\ControlStructure\NoUnneededCurlyBracesFixer: ~
  PhpCsFixer\Fixer\ClassNotation\NoUnneededFinalMethodFixer: ~
  PhpCsFixer\Fixer\CastNotation\NoUnsetCastFixer: ~
  PhpCsFixer\Fixer\ControlStructure\NoUselessElseFixer: ~
  PhpCsFixer\Fixer\ReturnNotation\NoUselessReturnFixer: ~
  PhpCsFixer\Fixer\ClassNotation\OrderedClassElementsFixer: ~
  PhpCsFixer\Fixer\PhpUnit\PhpUnitInternalClassFixer: ~
  PhpCsFixer\Fixer\PhpUnit\PhpUnitMethodCasingFixer: ~
  PhpCsFixer\Fixer\PhpUnit\PhpUnitOrderedCoversFixer: ~
  PhpCsFixer\Fixer\PhpUnit\PhpUnitTestClassRequiresCoversFixer: ~
  PhpCsFixer\Fixer\Phpdoc\PhpdocAddMissingParamAnnotationFixer: ~
  PhpCsFixer\Fixer\Phpdoc\PhpdocNoEmptyReturnFixer: ~
  PhpCsFixer\Fixer\Phpdoc\PhpdocOrderFixer: ~
  PhpCsFixer\Fixer\Phpdoc\PhpdocTypesOrderFixer: ~
  PhpCsFixer\Fixer\Phpdoc\PhpdocVarAnnotationCorrectOrderFixer: ~
  PhpCsFixer\Fixer\ClassNotation\ProtectedToPrivateFixer: ~
  PhpCsFixer\Fixer\ReturnNotation\ReturnAssignmentFixer: ~
  PhpCsFixer\Fixer\StringNotation\SimpleToComplexStringVariableFixer: ~
  PhpCsFixer\Fixer\Comment\SingleLineCommentStyleFixer: ~

parameters:
  skip:
    PhpCsFixer\Fixer\FunctionNotation\SingleLineThrowFixer: ~
