name: tests

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  ecs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.1, 7.2, 7.3, 7.4, 8.0]
        include:
          - php: '8.1'
            flags: "--ignore-platform-req=php"

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Setup PHP
        uses: shivammathur/setup-php@2.13.0
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, xdebug
          coverage: true

      - name: Install dependencies
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: highest
          composer-options: ${{ matrix.flags }}

      - name: Execute tests
        run: composer run-script test
