name: tests

on:
  pull_request:
  push:
    branches:
      - master
      - '[0-9]+.x'
  schedule:
    - cron: '0 0 * * *'

jobs:
  ecs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', 8.1, 8.2, 8.3]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@2.28.0
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, xdebug
          coverage: true

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: highest

      - name: Execute tests
        run: composer run-script test
